### ISSUE TITLE
Apps transforms not updating when worn

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/app#20]
Right now, apps are not updating when we wear them.

The bind is getting called properly, the app is getting worn, the problem seems to be that wearupdate is not getting called on the remoteplayer. We need to make sure the wearupdate function gets called on both remote players and local players.

**Comment by alisaad673** [comment]
As it can be seen in the video, The Wearable items are not getting replicated in the remote instances.

https://user-images.githubusercontent.com/35926530/163594265-d5177dbd-f053-4174-8ec7-8e4382a01a6c.mp4

**Comment by metadev26** [comment]
https://user-images.githubusercontent.com/99482765/164303556-b1e0eb96-185e-4613-928f-12d132b46258.mp4

Fixed this issue by changing the wearupdate function.

**Comment by anu-nexus** [comment]
It can be seen in the give video, The Wearable items are not getting replicated in the remote instances even remote instance get hanged. 
Steps to replicate
- I open Erithor room in both windows
- now remote player is moving like local player
- When i pressed e, then local player grabbed the sword
- And the screen of remote player was hanged
For reference, kindly see the attached [video]

**Comment by anu-nexus** [comment]
It can be seen in the give video, The Wearable items are not getting replicated in the remote instances even remote instance get hanged.
Steps to replicate

I open Erithor room in both windows
now remote player is moving like local player
When i pressed e, then local player grabbed the sword
And the screen of remote player was hanged
For reference, kindly see the attached [video]

https://user-images.githubusercontent.com/101788714/164718109-6ec3ff3d-d478-47b4-9b63-eadf6f30baec.mp4

**Comment by lalalune** [comment]
This has been fixed, was a separate null ref issue.

**Comment by anu-nexus** [comment]
When I retested this issue, I found that both player are able to wear sword but animation is happening at only local player. 
For reference, Kindly see the attached video:
https://www.awesomescreenshot.com/video/8727500?key=ec25a520c91d699410cd663abfe4d3a9
