### ISSUE TITLE
Check physics of networked characters

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/app#23]
It seems like characters should be able to collide with each other, but their colliders are not updating with their player movement in space. We should figure out why. Maybe we're disabling or not moving them? We probably want collision so players can hit each other with stuff.

**Comment by alisaad673** [comment]
1-Right now, once we create a room and enter the room from another instance too, There is no collision between avatars. As can be seen in the video. 
2-But Refreshing one of the instance brings the collision back. But the collision is back in only one of the instances, not both.
3- If we try to refresh both the instances to get collision in both, We instead lose collision in both the instances again.

https://user-images.githubusercontent.com/35926530/163592714-405b02df-5d67-46d6-9ec7-0f229214cfff.mp4

Refreshing the instance:

https://user-images.githubusercontent.com/35926530/163592728-933a6343-667f-4335-b6b9-24065ee2b02e.mp4

**Comment by lalalune** [comment]
This has been fixed, just need to QA and make sure collider deletes from PhysX when player leaves

**Comment by anu-nexus** [comment]
This issue has been resolved.

https://user-images.githubusercontent.com/101788714/170948342-1cf37f01-458f-44be-808b-bea0105ba122.mp4
