### ISSUE TITLE
Footsteps play while on vehicle

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/app#25]
Right now the footstep SFX are playing while the player is on the vehicle. We should check for 'sit' action and not do that.

**Comment by alisaad673** [comment]
While riding vehicles/dragon, the sound that is played right now is same as footsteps walk/run sfx. This is a general issue that also exists in webaverse/master and not only related to multiplayer. Video attached.

https://user-images.githubusercontent.com/35926530/163586023-db06a2cc-ea1a-4b55-beea-cdd124288b4f.mp4

**Comment by 0reo** [comment]
this issue should probably be closed in favor of this https://github.com/webaverse/app/issues/2387

**Comment by anu-nexus** [comment]
This issue has been resolved. Kindly watch video for reference.

https://user-images.githubusercontent.com/101788714/171146426-c5bc9724-8557-4665-902b-a0a67f7452be.mp4
