### ISSUE TITLE
Flying should release any pet, vehicle or mount

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/app#27]
Right now if I fly ('f') my character will fly off, but I'm still attached to the mount. This causes state issues.

**Comment by anu-nexus** [comment]
During flying, vehicle is releasing but pet is still attached. Kindly see the attached video:

https://user-images.githubusercontent.com/101788714/165459900-55f8054c-13d9-41d9-a831-3089cae50bd0.mp4

Thanks
