### ISSUE TITLE
Object not detatching

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/app#32]
When I pick up, object attaches. When I let go, object stays attached on remote player.

![image](https://user-images.githubusercontent.com/18633264/164713217-669fda97-886b-4f26-a42b-696d324096ae.png)

**Comment by anu-nexus** [comment]
This issue has been resolved. Kindly watch video for reference.

https://user-images.githubusercontent.com/101788714/170955326-91ecc268-23d6-4ffb-9e5e-b564498ceb92.mp4
