### ISSUE TITLE
Dropped wearable stays in release position on local instead of resetting pose

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/app#39]
![image](https://user-images.githubusercontent.com/18633264/164959117-dc6d8497-2e2e-4d9e-b826-5fb452f51c83.png)

**Comment by anu-nexus** [comment]
This issue has been verified. Kindly watch video for reference.

https://user-images.githubusercontent.com/101788714/170979920-dafeb83a-e7f1-49ba-baf5-df8c7f674d1d.mp4
