### ISSUE TITLE
Sync world objects in multiplayer:

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/app#4]
https://github.com/webaverse/app/issues/1479

**Comment by anu-nexus** [comment]
I replicate this issue by clicking on world option from right side menu. It shows all wearable  object and light available in current scene. But when we click on light and object, some issue is showing. Kindly watch video for reference:

https://user-images.githubusercontent.com/101788714/170930205-7780a196-8e93-48d1-b181-bf38cf26ef7a.mp4


https://user-images.githubusercontent.com/101788714/170930230-93b19f4d-9380-40dd-9d2a-713dc8d18bda.mp4
